FROM node:22-bullseye-slim

WORKDIR /usr/app

COPY package.json .
RUN npm install
RUN npm install -g nodemon

COPY . .

EXPOSE 8080

RUN npm run build
#CMD ["nodemon", "dist/app.js"]
CMD ["nodemon", "--watch", "src", "--ext", "ts,json", "--exec", "ts-node", "src/app.ts"]
